sequenceDiagram
        actor Alice
        actor Bob
        actor hanna
        autonumber
        Alice->>Bob: new msg
        Bob->>hanna: take
        rect rgb(250,250,200)
                hanna->>Alice: Hit
                rect rgb(250,0,200)
                        hanna->>Bob:Kiss    
                end    
        end

